import type { Metadata } from 'next';
import './globals.css';
import '../../public/scss/main.scss';
import localFont from 'next/font/local';
import Provider from '@/state/provider';
import { Chrome } from '@/components/shared/layout/chrome';
import { SquircleNoScript } from '@squircle-js/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Inter Display — the optical-size cut of Inter, tuned for larger text.
// It only ships as static weights, so we load the six the app actually uses.
const interDisplay = localFont({
  src: [
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-Light-subset.woff2', weight: '300', style: 'normal' },
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-Regular-subset.woff2', weight: '400', style: 'normal' },
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-Medium-subset.woff2', weight: '500', style: 'normal' },
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-SemiBold-subset.woff2', weight: '600', style: 'normal' },
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-Bold-subset.woff2', weight: '700', style: 'normal' },
    { path: '../../node_modules/inter-ui/display-latin/InterDisplay-ExtraBold-subset.woff2', weight: '800', style: 'normal' },
  ],
  display: 'swap',
  variable: '--font-inter-display',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interDisplay.variable}>
      <head>
        {/* Keeps squircled elements from flashing square before hydration. */}
        <SquircleNoScript />
      </head>
      <Provider>
        <body>
          <Chrome>{children}</Chrome>
        </body>
      </Provider>
    </html>
  );
}
