import type { Metadata } from 'next';
import './globals.css';
import '../../public/scss/main.scss';
import { Nunito } from 'next/font/google';
import { GeistSans } from 'geist/font/sans';
import Provider from '@/state/provider';
import { Layout } from '@/components/shared/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const nunito = Nunito({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
  // 👇 Add variable to our object
  variable: '--font-family-nunito',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} ${GeistSans.variable}`}>
      <Provider>
        <body>
          <Layout>{children}</Layout>
        </body>
      </Provider>
    </html>
  );
}
